In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) 
print(arr)
print(type(arr))
print(arr.shape)
print(arr.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int32


In [102]:
# arr2 = np.zeros(2)
# print(arr2)

# arr2 = np.ones(2)
# print(arr2)

arr2 = np.empty((3,2),int)
print(type(arr2.dtype))
arr2.ndim # number of dimensions

<class 'numpy.dtypes.Int32DType'>


2

In [53]:
arr2d = np.array([
    [1,2,3],
    [False,True,False],
    ["a","b","c"]
])
arr2d.size

9

In [117]:
arr3 = np.random.randint(1,10,size=(6,6))
arr3

array([[7, 1, 6, 4, 6, 9],
       [6, 1, 5, 9, 2, 2],
       [1, 6, 5, 1, 7, 8],
       [1, 3, 7, 2, 1, 9],
       [7, 8, 2, 9, 1, 3],
       [2, 1, 7, 7, 3, 5]])

In [ ]:
#boolean indexing
arr3[arr3>5]
arr3[arr3==5]
arr3[arr3 %2 == 1]

array([7, 5, 1, 7, 3, 3, 1, 3, 7, 7, 1, 9])

In [101]:
#fancey indexing
arr3[[0,1],[1,2]]

array([8, 3])

In [120]:
#slicing [row start:end:step, col start:end:step]
print(arr3)
arr3[::2,3::3]

[[7 1 6 4 6 9]
 [6 1 5 9 2 2]
 [1 6 5 1 7 8]
 [1 3 7 2 1 9]
 [7 8 2 9 1 3]
 [2 1 7 7 3 5]]


array([[4],
       [1],
       [9]])

In [131]:
arr4 = np.ones((5,5),dtype=int)
arr4[1:-1, 1:-1] = 0
arr4[2,2] = 9
arr4

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
a = np.ones((5,1),dtype=int)
b = np.full((5,5),2,dtype=int)

print(a+b)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [171]:
arr5 = np.array([0,0,False])
arr5.any()

False

In [183]:
arr6 = np.arange(1,10)
arr6 = arr6.reshape(3,3)
print(arr6)
arr6.transpose()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(123)

# Generate random numbers
random_numbers = np.random.rand(3)
print("First set of random numbers:", random_numbers)

# Generate another set of random numbers
another_set = np.random.rand(3)
print("Second set of random numbers:", another_set)

# Reset the seed to the same value
np.random.seed(123)

# Generate the same random numbers again
repeated_numbers = np.random.rand(3)
print("Repeated random numbers:", repeated_numbers)

# Check if the repeated numbers are the same as the first set
print("Are the first and repeated sets the same?", np.array_equal(random_numbers, repeated_numbers))  # Output: True


First set of random numbers: [0.69646919 0.28613933 0.22685145]
Second set of random numbers: [0.55131477 0.71946897 0.42310646]
Repeated random numbers: [0.69646919 0.28613933 0.22685145]
Are the first and repeated sets the same? True
